### STAGE 1: Build ###13.7-alpine3.10, 
FROM node:13.7-alpine3.10 AS build
WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN npm install
COPY . .
RUN npm run build
### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY --from=build /usr/src/app/dist/aston-villa-app  /usr/share/nginx/html